# Generated by Django 5.0.7 on 2024-08-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
