# Generated by Django 5.0.7 on 2024-08-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
