# Generated by Django 5.0.7 on 2024-08-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_personal_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personal_detail',
            new_name='personal_details',
        ),
    ]
